sura_teleop:
  ros__parameters:
    rate: 20.0
    joy_topic: /joy
    controller_switch_service: /controller_manager/switch_controller

    body_force_controller:
      name: body_force_controller

    body_velocity_controller:
      name: body_velocity_controller
      setpoint_topic: /body_velocity_controller/setpoint

    position_hold_controller:
      name: position_hold_controller
      feedforward_topic: /position_hold_controller/feedforward

    stabilize_controller:
      name: stabilize_controller
      feedforward_topic: /stabilize_controller/feedforward
      enable_roll_pitch_service: /stabilize_controller/enable_roll_pitch
      disable_roll_pitch_service: /stabilize_controller/disable_roll_pitch
      feedforward_gain_x: 20.0
      feedforward_gain_y: 20.0
      feedforward_gain_z: 90.0
      feedforward_gain_roll: 20.0
      feedforward_gain_pitch: 20.0
      feedforward_gain_yaw: 1.0

    depth_hold_controller:
      name: depth_hold_controller
      feedforward_topic: /depth_hold_controller/feedforward
      enable_roll_pitch_service: /depth_hold_controller/enable_roll_pitch
      disable_roll_pitch_service: /depth_hold_controller/disable_roll_pitch
      feedforward_gain_x: 20.0
      feedforward_gain_y: 20.0
      feedforward_gain_z: 90.0
      feedforward_gain_roll: 20.0
      feedforward_gain_pitch: 20.0
      feedforward_gain_yaw: 1.0

    buttons:
      a: 0
      b: 1
      x: 2
      lb: 4
      rb: 5
      y: 3

    axes:
      hat_vertical: 7
      surge: 4
      sway: 3
      yaw: 0
      heave: 1
      roll: 3
      pitch: 4

    scales:
      surge: 1.0
      sway: -1.0
      heave: 1.0
      yaw: -1.0
      roll: -1.0
      pitch: -1.0

    deadzone: 0.05
