sura_teleop:
  ros__parameters:
    rate: 20.0
    joy_topic: /joy
    controller_switch_service: /blueboat/controller/controller_manager/switch_controller
    controller_list_service: /blueboat/controller/controller_manager/list_controllers

    body_force_controller:
      name: body_force
      command_topic: /blueboat/controller/body_force/command
      feedforward_gain_x: 350.0
      feedforward_gain_y: 0.0
      feedforward_gain_z: 0.0
      feedforward_gain_roll: 0.0
      feedforward_gain_pitch: 0.0
      feedforward_gain_yaw: 20.0

    body_velocity_controller:
      name: body_velocity
      setpoint_topic: /cmd_vel

    position_hold_controller:
      name: blueboat_unused_position_hold_controller
      feedforward_topic: /cmd_vel

    stabilize_controller:
      name: blueboat_unused_stabilize_controller
      feedforward_topic: /body_force/command
      enable_roll_pitch_service: /blueboat/controller/blueboat_unused_stabilize_controller/enable_roll_pitch
      disable_roll_pitch_service: /blueboat/controller/blueboat_unused_stabilize_controller/disable_roll_pitch
      feedforward_gain_x: 350.0
      feedforward_gain_y: 0.0
      feedforward_gain_z: 0.0
      feedforward_gain_roll: 0.0
      feedforward_gain_pitch: 0.0
      feedforward_gain_yaw: 20.0

    depth_hold_controller:
      name: body_force
      feedforward_topic: /blueboat/controller/body_force/command
      enable_roll_pitch_service: /blueboat/controller/body_force/enable_roll_pitch
      disable_roll_pitch_service: /blueboat/controller/body_force/disable_roll_pitch
      feedforward_gain_x: 350.0
      feedforward_gain_y: 0.0
      feedforward_gain_z: 0.0
      feedforward_gain_roll: 0.0
      feedforward_gain_pitch: 0.0
      feedforward_gain_yaw: 20.0

    buttons:
      a: 0
      b: 1
      x: 2
      lb: 4
      rb: 5
      y: 3
      left_stick: 10
      right_stick: 10

    axes:
      hat_horizontal: 6
      hat_vertical: 7
      surge: 1
      sway: 3
      yaw: 3
      heave: 1
      roll: 3
      pitch: 4
      lt: 2
      rt: 5

    scales:
      surge: 0.35
      sway: 0.0
      heave: 0.0
      yaw: 0.3
      roll: 0.0
      pitch: 0.0

    deadzone: 0.2
